import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://openclaw-zh.pages.dev',
  integrations: [
    starlight({
      title: 'OpenClaw 中文网',
      description:
        'OpenClaw 开源 AI 智能体中文文档 — 自托管个人 AI 助手，支持 WhatsApp、Telegram、Discord、飞书、钉钉、企业微信等 20+ 聊天平台。',
      defaultLocale: 'root',
      locales: {
        root: { label: '简体中文', lang: 'zh-CN' },
      },
      logo: {
        src: './src/assets/pixel-lobster.svg',
      },
      favicon: '/assets/pixel-lobster.svg',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/openclaw/openclaw',
        },
      ],
      head: [
        {
          tag: 'meta',
          attrs: {
            property: 'og:image',
            content: '/assets/og-default.png',
          },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:site_name', content: 'OpenClaw 中文网' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:locale', content: 'zh_CN' },
        },
      ],
      customCss: ['./src/styles/custom.css'],
      expressiveCode: {
        themes: ['min-dark', 'min-light'],
      },
      sidebar: [
        // ── 快速开始 ──
        {
          label: '快速开始',
          items: [
            'docs-home',
            'start/showcase',
            'concepts/features',
            {
              label: '第一步',
              items: [
                'start/getting-started',
                'start/onboarding-overview',
                'start/wizard',
                'start/onboarding',
              ],
            },
            {
              label: '指南',
              items: [
                'start/openclaw',
                'start/wizard-cli-reference',
                'start/wizard-cli-automation',
              ],
            },
          ],
        },
        // ── 安装 ──
        {
          label: '安装',
          collapsed: true,
          items: [
            'install',
            'install/installer',
            {
              label: '安装方式',
              items: [
                'install/docker',
                'install/podman',
                'install/nix',
                'install/ansible',
                'install/bun',
              ],
            },
            {
              label: '维护',
              items: [
                'install/updating',
                'install/migrating',
                'install/uninstall',
              ],
            },
            {
              label: '托管与部署',
              items: [
                'vps',
                'install/fly',
                'install/hetzner',
                'install/gcp',
                'install/macos-vm',
                'install/exe-dev',
                'install/railway',
                'install/render',
                'install/northflank',
              ],
            },
            'install/development-channels',
          ],
        },
        // ── 消息渠道 ──
        {
          label: '消息渠道',
          collapsed: true,
          items: [
            'channels',
            {
              label: '消息平台',
              collapsed: true,
              items: [
                'channels/bluebubbles',
                'channels/discord',
                'channels/feishu',
                'channels/googlechat',
                'channels/imessage',
                'channels/irc',
                'channels/line',
                'channels/matrix',
                'channels/mattermost',
                'channels/msteams',
                'channels/nextcloud-talk',
                'channels/nostr',
                'channels/signal',
                'channels/synology-chat',
                'channels/slack',
                'channels/telegram',
                'channels/tlon',
                'channels/twitch',
                'channels/whatsapp',
                'channels/zalo',
                'channels/zalouser',
              ],
            },
            {
              label: '配置',
              items: [
                'channels/pairing',
                'channels/group-messages',
                'channels/groups',
                'channels/broadcast-groups',
                'channels/channel-routing',
                'channels/location',
                'channels/troubleshooting',
              ],
            },
          ],
        },
        // ── 代理 ──
        {
          label: '代理',
          collapsed: true,
          items: [
            {
              label: '基础',
              items: [
                'pi',
                'concepts/architecture',
                'concepts/agent',
                'concepts/agent-loop',
                'concepts/system-prompt',
                'concepts/context',
                'concepts/agent-workspace',
                'concepts/oauth',
              ],
            },
            'start/bootstrapping',
            {
              label: '会话与记忆',
              items: [
                'concepts/session',
                'concepts/session-pruning',
                'concepts/session-tool',
                'concepts/memory',
                'concepts/compaction',
              ],
            },
            {
              label: '多代理',
              items: ['concepts/multi-agent', 'concepts/presence'],
            },
            {
              label: '消息与投递',
              items: [
                'concepts/messages',
                'concepts/streaming',
                'concepts/retry',
                'concepts/queue',
              ],
            },
          ],
        },
        // ── 工具 ──
        {
          label: '工具',
          collapsed: true,
          items: [
            'tools',
            {
              label: '内置工具',
              collapsed: true,
              items: [
                'tools/apply-patch',
                'brave-search',
                'perplexity',
                'tools/diffs',
                'tools/pdf',
                'tools/elevated',
                'tools/exec',
                'tools/exec-approvals',
                'tools/firecrawl',
                'tools/llm-task',
                'tools/lobster',
                'tools/loop-detection',
                'tools/reactions',
                'tools/thinking',
                'tools/web',
              ],
            },
            {
              label: '浏览器',
              items: [
                'tools/browser',
                'tools/browser-login',
                'tools/chrome-extension',
                'tools/browser-linux-troubleshooting',
              ],
            },
            {
              label: '代理协作',
              items: [
                'tools/agent-send',
                'tools/subagents',
                'tools/acp-agents',
                'tools/multi-agent-sandbox-tools',
              ],
            },
            {
              label: '技能',
              items: [
                'tools/creating-skills',
                'tools/slash-commands',
                'tools/skills',
                'tools/skills-config',
                'tools/clawhub',
                'tools/plugin',
              ],
            },
            {
              label: '扩展',
              collapsed: true,
              items: [
                'plugins/community',
                'plugins/voice-call',
                'plugins/zalouser',
                'plugins/manifest',
                'plugins/agent-tools',
                'prose',
              ],
            },
            {
              label: '自动化',
              collapsed: true,
              items: [
                'automation/hooks',
                'automation/cron-jobs',
                'automation/cron-vs-heartbeat',
                'automation/troubleshooting',
                'automation/webhook',
                'automation/gmail-pubsub',
                'automation/poll',
                'automation/auth-monitoring',
              ],
            },
            {
              label: '媒体与设备',
              collapsed: true,
              items: [
                'nodes',
                'nodes/troubleshooting',
                'nodes/media-understanding',
                'nodes/images',
                'nodes/audio',
                'nodes/camera',
                'nodes/talk',
                'nodes/voicewake',
                'nodes/location-command',
                'tts',
              ],
            },
          ],
        },
        // ── 模型 ──
        {
          label: '模型',
          collapsed: true,
          items: [
            'providers',
            'providers/models',
            'concepts/models',
            {
              label: '配置',
              items: ['concepts/model-providers', 'concepts/model-failover'],
            },
            {
              label: '提供商',
              collapsed: true,
              items: [
                'providers/anthropic',
                'providers/bedrock',
                'providers/cloudflare-ai-gateway',
                'providers/claude-max-api-proxy',
                'providers/deepgram',
                'providers/github-copilot',
                'providers/huggingface',
                'providers/kilocode',
                'providers/litellm',
                'providers/glm',
                'providers/minimax',
                'providers/moonshot',
                'providers/mistral',
                'providers/nvidia',
                'providers/ollama',
                'providers/openai',
                'providers/opencode-go',
                'providers/opencode',
                'providers/openrouter',
                'providers/qianfan',
                'providers/qwen',
                'providers/synthetic',
                'providers/together',
                'providers/vercel-ai-gateway',
                'providers/venice',
                'providers/vllm',
                'providers/xiaomi',
                'providers/zai',
              ],
            },
          ],
        },
        // ── 平台 ──
        {
          label: '平台',
          collapsed: true,
          items: [
            {
              label: '平台概览',
              items: [
                'platforms',
                'platforms/macos',
                'platforms/linux',
                'platforms/windows',
                'platforms/android',
                'platforms/ios',
                'platforms/digitalocean',
                'platforms/oracle',
                'platforms/raspberry-pi',
              ],
            },
            {
              label: 'macOS 配套应用',
              collapsed: true,
              items: [
                'platforms/mac/dev-setup',
                'platforms/mac/menu-bar',
                'platforms/mac/voicewake',
                'platforms/mac/voice-overlay',
                'platforms/mac/webchat',
                'platforms/mac/canvas',
                'platforms/mac/child-process',
                'platforms/mac/health',
                'platforms/mac/icon',
                'platforms/mac/logging',
                'platforms/mac/permissions',
                'platforms/mac/remote',
                'platforms/mac/signing',
                'platforms/mac/release',
                'platforms/mac/bundled-gateway',
                'platforms/mac/xpc',
                'platforms/mac/skills',
                'platforms/mac/peekaboo',
              ],
            },
          ],
        },
        // ── 网关与运维 ──
        {
          label: '网关与运维',
          collapsed: true,
          items: [
            'gateway',
            {
              label: '配置与运维',
              collapsed: true,
              items: [
                'gateway/configuration',
                'gateway/configuration-reference',
                'gateway/configuration-examples',
                'gateway/authentication',
                'auth-credential-semantics',
                'gateway/secrets',
                'gateway/secrets-plan-contract',
                'gateway/trusted-proxy-auth',
                'gateway/health',
                'gateway/heartbeat',
                'gateway/doctor',
                'gateway/logging',
                'gateway/gateway-lock',
                'gateway/background-process',
                'gateway/multiple-gateways',
                'gateway/troubleshooting',
              ],
            },
            {
              label: '安全与沙箱',
              items: [
                'gateway/security',
                'gateway/sandboxing',
                'gateway/sandbox-vs-tool-policy-vs-elevated',
              ],
            },
            {
              label: '协议与 API',
              collapsed: true,
              items: [
                'gateway/protocol',
                'gateway/bridge-protocol',
                'gateway/openai-http-api',
                'gateway/openresponses-http-api',
                'gateway/tools-invoke-http-api',
                'gateway/cli-backends',
                'gateway/local-models',
              ],
            },
            {
              label: '网络与发现',
              items: [
                'gateway/network-model',
                'gateway/pairing',
                'gateway/discovery',
                'gateway/bonjour',
              ],
            },
            {
              label: '远程访问',
              items: [
                'gateway/remote',
                'gateway/remote-gateway-readme',
                'gateway/tailscale',
              ],
            },
            {
              label: '安全文档',
              items: [
                'security/formal-verification',
                { label: '安全与信任', link: '/security/readme/' },
                { label: '威胁模型', link: '/security/threat-model-atlas/' },
                { label: '贡献威胁模型', link: '/security/contributing-threat-model/' },
              ],
            },
            {
              label: 'Web 界面',
              items: [
                'web',
                'web/control-ui',
                'web/dashboard',
                'web/webchat',
                'web/tui',
              ],
            },
          ],
        },
        // ── 参考 ──
        {
          label: '参考',
          collapsed: true,
          items: [
            {
              label: 'CLI 命令',
              collapsed: true,
              items: [
                'cli',
                'cli/acp',
                'cli/agent',
                'cli/agents',
                'cli/approvals',
                'cli/browser',
                'cli/channels',
                'cli/clawbot',
                'cli/completion',
                'cli/config',
                'cli/configure',
                'cli/cron',
                'cli/daemon',
                'cli/dashboard',
                'cli/devices',
                'cli/directory',
                'cli/dns',
                'cli/docs',
                'cli/doctor',
                'cli/gateway',
                'cli/health',
                'cli/hooks',
                'cli/logs',
                'cli/memory',
                'cli/message',
                'cli/models',
                'cli/node',
                'cli/nodes',
                'cli/onboard',
                'cli/pairing',
                'cli/plugins',
                'cli/qr',
                'cli/reset',
                'cli/sandbox',
                'cli/secrets',
                'cli/security',
                'cli/sessions',
                'cli/setup',
                'cli/skills',
                'cli/status',
                'cli/system',
                'cli/tui',
                'cli/uninstall',
                'cli/update',
                'cli/voicecall',
                'cli/webhooks',
              ],
            },
            {
              label: 'RPC 与 API',
              items: ['reference/rpc', 'reference/device-models'],
            },
            {
              label: '模板',
              collapsed: true,
              items: [
                { label: 'AGENTS.default', link: '/reference/agentsdefault/' },
                { label: 'AGENTS.md', link: '/reference/templates/agents/' },
                { label: 'BOOT.md', link: '/reference/templates/boot/' },
                { label: 'BOOTSTRAP.md', link: '/reference/templates/bootstrap/' },
                { label: 'HEARTBEAT.md', link: '/reference/templates/heartbeat/' },
                { label: 'IDENTITY.md', link: '/reference/templates/identity/' },
                { label: 'SOUL.md', link: '/reference/templates/soul/' },
                { label: 'TOOLS.md', link: '/reference/templates/tools/' },
                { label: 'USER.md', link: '/reference/templates/user/' },
              ],
            },
            {
              label: '技术参考',
              items: [
                'reference/wizard',
                'reference/token-use',
                'reference/secretref-credential-surface',
                'reference/prompt-caching',
                'reference/api-usage-costs',
                'reference/transcript-hygiene',
                'date-time',
              ],
            },
            {
              label: '概念内部机制',
              items: [
                'concepts/typebox',
                'concepts/markdown-formatting',
                'concepts/typing-indicators',
                'concepts/usage-tracking',
                'concepts/timezone',
              ],
            },
            'reference/credits',
            {
              label: '发布说明',
              items: [{ label: '发布清单', link: '/reference/releasing/' }, 'reference/test'],
            },
            {
              label: '实验性功能',
              collapsed: true,
              items: [
                'design/kilo-gateway-integration',
                'experiments/onboarding-config-protocol',
                'experiments/plans/acp-thread-bound-agents',
                'experiments/plans/acp-unified-streaming-refactor',
                'experiments/plans/browser-evaluate-cdp-refactor',
                'experiments/plans/openresponses-gateway',
                'experiments/plans/pty-process-supervision',
                'experiments/plans/session-binding-channel-agnostic',
                'experiments/research/memory',
                'experiments/proposals/model-config',
              ],
            },
          ],
        },
        // ── 帮助 ──
        {
          label: '帮助',
          collapsed: true,
          items: [
            'help',
            'help/troubleshooting',
            'help/faq',
            'start/lore',
            {
              label: '环境与调试',
              items: [
                'help/environment',
                'help/debugging',
                'help/testing',
                'help/scripts',
                'debug/node-issue',
                'diagnostics/flags',
              ],
            },
            'install/node',
            'reference/session-management-compaction',
            {
              label: '开发者设置',
              items: ['start/setup', 'pi-dev'],
            },
            'ci',
            {
              label: '文档元信息',
              items: ['start/hubs', 'start/docs-directory'],
            },
          ],
        },
        // ── 速查表 ──
        {
          label: '速查表',
          collapsed: true,
          items: [
            'cheatsheet/cli-commands',
            'cheatsheet/slash-commands',
          ],
        },
      ],
    }),
  ],
});
